language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - g++-7
      - libx11-dev
      - libxrandr-dev
      - libudev-dev
      - clang-6.0

matrix:
  include:
    - os: linux
      sudo: false
      env: CXX_EXE=/usr/bin/g++-7 CC_EXE=/usr/bin/gcc-7 GCOV=/usr/bin/gcov-7

install:
  pip install --user conan

script:
  - export CXX=$CXX_EXE
  - export CC=$CC_EXE
  - echo $CXX
  - $CXX --version
  - mkdir build
  - cd build
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
  - conan install .. --build missing
  - cmake -D CMAKE_BUILD_TYPE:STRING=Debug -D ENABLE_COVERAGE:BOOL=TRUE ..
  - VERBOSE=1 cmake --build . -- -j2
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) -x $GCOV 2>/dev/null



