language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - g++-8
      - libx11-dev
      - libxrandr-dev
      - libudev-dev
      - clang-6.0

matrix:
  include:
    - os: linux
      sudo: false
      env: CXX=/usr/bin/clang++-6.0 CC=/usr/bin/clang-6.0 GCOV=/usr/bin/llvm-cov

install:
  pip install --user conan

script:
  - echo $CXX
  - $CXX --version
  - mkdir build
  - cd build
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
  - conan install .. --build missing
  - cmake -D CMAKE_BUILD_TYPE:STRING=Debug -D ENABLE_COVERAGE:BOOL=TRUE ..
  - VERBOSE=1 cmake --build . -- -j2
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash) 2>/dev/null



