version: 2
jobs:
  build:
    docker:
      - image: lasote/conangcc8
  steps:
    - checkout
    - run: |
      gcc-8 --version
      cmake --version
      conan --version
      export CXX=`which g++-8`
      export CC=`which gcc-8`
      mkdir build
      cd build
      conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
      conan install .. --build missing
      cmake  $CMAKE_OPTS ..
      VERBOSE=1 cmake --build . -- -j2
      ctest -j2



